-- 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE_NAME};

-- 사용자 생성 및 권한 설정
CREATE USER IF NOT EXISTS '${MYSQL_USER_NAME}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE_NAME}.* TO '${MYSQL_USER_NAME}'@'%';
FLUSH PRIVILEGES;