version: '3.9' # docker 버전

services:
  mariadb:
    container_name: db
    image: mariadb:v_final
    env_file: ../.env
    environment:
      - MYSQL_MYSQL_LOCALHOST_USER=${MARIADB_LOCALHOST_USER}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ${MARIADB_PATH}/data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - db_data

volumes:
  db_data: {}

networks:
  intra:
    driver: bridge