version: '3.9' # docker 버전

services:
  mariadb:
    container_name: db
    build: ./requirements/mariadb/.
    image: mariadb:v_final
    volumes:
      - db_data:/var/lib/mysql
      - ./requirements/mariadb/my.cnf:/etc/mysql/my.cnf
    networks:
      - wordpress_network
    restart: always
    env_file:
      - ../.env

volumes:
  db_data:
    driver: local
    driver_opts:
      device: /home/hyehan/Desktop/Inception/srcs/mariadb
      o: bind
      type: none

networks:
  wordpress_network:
    driver: bridge