version: '3.9' # docker 버전

services:
  mariadb:
    container_name: db
    build:
      context: requirements/mariadb/.
      dockerfile: dockerfile
    image: mariadb:v_final
    volumes:
      - db_data: /var/lib/mysql
    networks:
      - wordpress_network
    restart: always
    env_file:
      - .env

volumes:
  db_data:

networks:
  wordpress_network:
    driver: bridge